import React from "react"
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/src/shared/Navbar"
import Hero from "@/src/components/home/Hero"
import { ChakraProvider } from '@chakra-ui/react'
import About from "@/src/components/home/About"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <div>
            <Hero />
            <About />
            {children}
          </div>
        </ChakraProvider>
      </body>
    </html>
  )
}
